import type { TripData } from "./types";

export const mockTrip: TripData = {
  id: 486,
  voucher: "VR-NZ4873",
  source: "Website Booking",
  siteStatus: "pending",
  issues: { critical: 2, total: 2, tags: ["Missing Deposit In"] },
  status: "new",
  customer: {
    name: "Harry Bui",
    phone: "+84 931 339 868",
    email: "haibui3520@gmail.com",
    lang: "VI",
  },
  dates: { start: "2026-05-04T10:00", end: "2026-05-07T10:00", days: 3 },
  pickup: "Tan Son Nhat International Airport",
  dropoff: "Tan Son Nhat International Airport",
  car: { name: "Mitsubishi Xpander", plate: "79A 425.92" },
  extras: [],
  notes: "",
  price: {
    base: 3870000,
    insurance: 0,
    extras: 0,
    afterHours: 300000,
    lateBooking: 300000,
    taxRate: 0.07,
  },
  payments: [
    {
      id: "1",
      type: "RENT",
      direction: "in",
      party: "Client → Sergey",
      amount: 475,
      currency: "USD",
      status: "Done",
      method: "Cash",
      date: "27/04/26 11:30",
      delta: 12540000,
    },
    {
      id: "2",
      type: "DEPOSIT",
      direction: "in",
      party: "Client → Unknown",
      amount: 0,
      currency: "VND",
      status: "Not Done",
      method: "Advance",
      date: "27/04/26 11:30",
    },
    {
      id: "3",
      type: "DEPOSIT",
      direction: "in",
      party: "Client → Sergey",
      amount: 600,
      currency: "USD",
      status: "Done",
      method: "Cash",
      date: "27/04/26 11:30",
      delta: 15840000,
    },
  ],
  terms: { mileage: "Unlimited", freeCancel: "24h before pickup", drivingRules: "Accepted", currency: "VND" },
};